ystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 3000

server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: calculadora
          uri: localhost:8081
          predicates:
            - Path=/api/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream