server:
  port: 8081

spring:
  application:
    name: calculadora
  #Configurações de conexão com a instância do RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass
    #Nome exchange a ser criado pelo projeto no output
  cloud:
    stream:
      bindings:
        output:
          destination: calculo.resultado
        canal-mensage:
          destination: valores
        input:
          destination: calculo.entrada
          group: teste

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
